### ISSUE TITLE
buttons dont work

### ISSUE THREAD

**Issue by bro-my-username-got-blocked** [Crazygird/crazygird.github.io#13]
The buttons for crazyggird dont work
[Screen recording 2023-03-12 20.04.58.webm](https://user-images.githubusercontent.com/125519936/224598861-d78c2e05-f472-4694-9a50-7c1ebd15c8eb.webm)

**Comment by Crazygird** [comment]
noob

**Comment by bro-my-username-got-blocked** [comment]
they weren't ok
