### ISSUE TITLE
Fix code scanning alert - DOM text reinterpreted as HTML

### ISSUE THREAD

**Issue by ghost** [Crazygird/crazygird.github.io#5]
Tracking issue for:
- [ ] https://github.com/Crazygird/Crazygird.github.io/security/code-scanning/1

fix plz

**Comment by Crazygird** [comment]
@Gamer-Guy12  pls help

**Comment by ghost** [comment]
aaaaaaa

**Comment by Crazygird** [comment]
i fixed it
