### ISSUE TITLE
Your site smells

### ISSUE THREAD

**Issue by SorenWidman** [Crazygird/crazygird.github.io#6]
no gemes, how do i become epoc gemr in class!?!?!?! i go back to roblox, no fun

**Comment by Crazygird** [comment]
dfajklsf

**Comment by Crazygird** [comment]
![Screenshot 2023-02-27 9 14 35 AM](https://user-images.githubusercontent.com/95974074/221633589-f9220053-11f6-43c1-a96c-99b70c769567.png)

**Comment by Crazygird** [comment]
ajfdklfjd;k
